// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALQSTRYJZF7Is7dTklNdT9ALYeijE-SJo',
    appId: '1:474877316901:android:004947ca8db14ad8b254cc',
    messagingSenderId: '474877316901',
    projectId: 'helloworld-155e1',
    databaseURL: 'https://helloworld-155e1-default-rtdb.firebaseio.com',
    storageBucket: 'helloworld-155e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqiQyuBbzIKKbv8Hht0-_cPT34XafLmIQ',
    appId: '1:474877316901:ios:9a9c51b87e312948b254cc',
    messagingSenderId: '474877316901',
    projectId: 'helloworld-155e1',
    databaseURL: 'https://helloworld-155e1-default-rtdb.firebaseio.com',
    storageBucket: 'helloworld-155e1.appspot.com',
    iosBundleId: 'com.example.volunteerAppv2',
  );
}
