name: volunteer_app
description: volunteer app

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.3
  overlay_support: ^2.1.0
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.3
  image_picker: ^1.1.2
  google_sign_in: 6.2.1
  flutter_local_notifications: ^17.2.1+2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

stripe_dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  excel: ^2.0.2
  path_provider: ^2.0.11
  provider: ^6.0.0
  stripe_payments: ^1.0.1

firebase_dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  excel: ^2.0.2
  path_provider: ^2.0.11
  firebase_core: ^2.10.0
  firebase_auth: ^4.8.0
  cloud_firestorm: ^4.8.0
flutter:
  uses-material-design: true

